Milestone 3: Style feature
PhillipUg/calculator-react pull request #5
Opened 2020-09-22 10:05 UTC by PhillipUg

### In this milestone, i have done the following;
- Used `flexbox` to layout Display and ButtonPanel Components
- Styled Display, ButtonPanel and Button Components
- Passed `color` and `wide` props to Button component
- Run linters and made sure everything is working properly

2020-09-22 16:38 UTC, fatymahmed requested changes
## Hi @PhillipUg 
You have done a great job on this milestone 👏👏
However, there are some things that we need to fix.
**Kindly check my comments below**

## Status: Changes Required ♻️
_Feel free to reach out to me on slack (Fatima) if you have any questions or need any help_

2020-09-22 16:40 UTC, fatymahmed commented on src/components/Display.js
>  );
- `Display` component should use flex display mode as mentioned on Pathwright, see [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone3/useFlex.png)

2020-09-22 16:40 UTC, fatymahmed commented on src/components/ButtonPanel.js
>    <div>
- `ButtonPanel` component should use flex display mode as mentioned on Pathwright, see [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone3/useFlex.png)

2020-09-22 17:11 UTC, PhillipUg commented
### Corrected the following;
- Used flex display mode to layout ButtonPanel and Display components

2020-09-23 01:12 UTC, jofer86 approved these changes
## `const PROJECT_STATUS = "APPROVED"` 🚀 🚀 🚀 
## :wave: :wave: Hello! I'm Jorge, and  I will be conducting this code review. Let me get a closer look 🔎 🔍 🔎 🔍 🕵🏼 
- Changes marked as **[OPTIONAL]** are not hard requirements but are nice to have.
- All of the required changes were done, this milestone is complete!!.
--------------------------------------------------------------------
**Rock on**  🤘🏼 
**_Jorge Fernando Rincón Figueroa._** 
Technical Support Engineer.

2020-09-23 04:27 UTC, merged